### ISSUE TITLE
Top level design not found

### ISSUE THREAD

**Issue by michaelengel** [lawrie/ulx3s_mac128#1]
With current yosys tools (Yosys 0.20+1 (git sha1 60a787fa5, clang 13.1.6 -fPIC -Os)), the synthesis is unable to find the correct top level module, perhaps related to [this problem](https://github.com/YosysHQ/yosys/issues/3055)?

Adding the parameter "-top mac128" to the yosys call in ulx3s/ulx3s.mk fixed the problem for me.

**Comment by lawrie** [comment]
Thanks. I have added this to my projects that I have used recently, but I have not touched this one for a while.

**Comment by lawrie** [comment]
I have pushed the change.
